#name: Azure Static Web Apps CI/CD
#
#on:
#  push:
#    branches:
#      - main
#  pull_request:
#    types: [opened, synchronize, reopened, closed]
#    branches:
#      - main
#
#jobs:
#  build_and_deploy_job:
#    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
#    runs-on: ubuntu-latest
#    name: Build and Deploy Job
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          submodules: true
#          lfs: false
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20'
#          cache: 'npm'
#          cache-dependency-path: 'FE/package-lock.json'
#
#      - name: Install and Build Base (No SSG)
#        run: |
#          cd FE
#          npm install
#          npm run build:stage:base
#
#      - name: Deploy to Azure Static Web Apps (Base)
#        id: builddeploy_base
#        uses: Azure/static-web-apps-deploy@v1
#        with:
#          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_PLANT_034DA0F03 }}
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          action: "upload"
#
#          skip_app_build: true
#          app_location: "FE/dist"
#          api_location: ""
#          output_location: ""
#
#      - name: Build SSG
#        run: |
#          cd FE
#          npm run build:stage:ssg
#
#      - name: Deploy to Azure Static Web Apps (SSG)
#        id: builddeploy_ssg
#        uses: Azure/static-web-apps-deploy@v1
#        with:
#          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_PLANT_034DA0F03 }}
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          action: "upload"
#
#          skip_app_build: true
#          app_location: "FE/dist"
#          api_location: ""
#          output_location: ""
#
#  close_pull_request_job:
#    if: github.event_name == 'pull_request' && github.event.action == 'closed'
#    runs-on: ubuntu-latest
#    name: Close Pull Request Job
#    steps:
#      - name: Close Pull Request
#        id: closepullrequest
#        uses: Azure/static-web-apps-deploy@v1
#        with:
#          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_PLANT_034DA0F03 }}
#          action: "close"
#          app_location: "/" # required parameter even for close action
