name: FE ACR Pipeline

on:
  push:
    branches: ['master', 'dev']
    paths: ['FE/**', '.github/workflows/fe.yml']
    tags: ['v*']

jobs:
  run-fe-pipeline:
    uses: ./.github/workflows/reusable-build-deploy.yml
    secrets: inherit
    with:
      service_path: 'FE'
      image_name: 'Kolsherut-FE'
      deployment_dev: 'kolsherut-fe-dev'
      deployment_stage: 'kolsherut-fe-stage'
      deployment_prod: 'kolsherut-fe-prod'
